# Generated by Django 3.0.8 on 2020-07-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200730_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='mojang_uuid',
        ),
    ]
